title: Advyth Ramachandran
description: PhD Student at the University of Colorado–Boulder
logo: img/IMG_5487.JPG
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one